Время разбивать камни
htmlacademy-ecmascript/977795-cinemaddict-17 pull request #3
Opened 2022-04-29 13:31 UTC by satananastyle

Делим код на блоки
Отрисовываем список фильмов
Отрисовываем попап

2022-04-29 14:59 UTC, AlexMasterov requested changes

2022-04-29 14:59 UTC, AlexMasterov commented on src/presenter/popap-presenter.js
> +    this.mainContainer = mainContainer;
```js
mainContainer instanceof Element      // true
this.mainContainer instanceof Element // true
```

[`Д 6`](https://up.htmlacademy.ru/ecmascript/17/criteries#d6)
> Используется единый стиль именования переменных

> если есть переменные, которые хранят [DOM-элемент](https://developer.mozilla.org/ru/docs/Web/API/Element) и содержат слово `Element`, **то это правило работает везде**

2022-04-29 14:59 UTC, AlexMasterov commented on src/presenter/popap-presenter.js
> +    const commentsWrap = this.mainContainer.querySelector('.film-details__comments-wrap');
[`Д 6`](https://up.htmlacademy.ru/ecmascript/17/criteries#d6)
> Используется единый стиль именования переменных

> если есть переменные, которые хранят [DOM-элемент](https://developer.mozilla.org/ru/docs/Web/API/Element) и содержат слово `Element`, **то это правило работает везде**

2022-04-29 14:59 UTC, AlexMasterov commented on src/presenter/films-presenter.js
> +    render(this.filmsComponent, this.mainContainer);
<details>
<summary>Проблема</summary>

```
films => main
films-list => films
films-list__container => films-list
film-card => films-list__container
film-card => films-list__container
film-card => films-list__container
film-card => films-list__container
film-card => films-list__container
films-list__show-more => films-list
```
</details>

Элемент с классом `.main` (= `this.mainContainer`) уже находится в нем, причем как видимый.

Весь код ниже производит множ. операции на элементе, который добавлен в DOM.

[`Б 35`](https://up.htmlacademy.ru/ecmascript/17/criteries#b35)
> Множественные DOM-операции производятся на элементах, которые не добавлены в DOM

2022-04-29 14:59 UTC, AlexMasterov commented on src/presenter/popap-presenter.js
> +    render(this.popapComponent, this.mainContainer);
<details>
<summary>Проблема</summary>

```
film-details => body
film-details__info-wrap => film-details__top-container
film-details__controls => film-details__top-container
film-details__comment => film-details__comments-wrap
film-details__comment => film-details__comments-wrap
film-details__comment => film-details__comments-wrap
film-details__comment => film-details__comments-wrap
film-details__new-comment => film-details__comments-wrap
```
</details>

`.film-details` => `body` (= `this.mainContainer`)

[`Б 35`](https://up.htmlacademy.ru/ecmascript/17/criteries#b35)
> Множественные DOM-операции производятся на элементах, которые не добавлены в DOM

2022-05-02 20:53 UTC, satananastyle commented on src/presenter/popap-presenter.js
> +    const commentsWrap = this.mainContainer.querySelector('.film-details__comments-wrap');
Будет ли корректно в `PopupView` создать отдельные методы, которые ищут эти дочерние узлы?
Например:

> getTopContainer() {
>     if (!this.element) {
>       this.element = createElement(this.getTemplate());
>     }
>     const topContainerElement = this.element.querySelector('.film-details__top-container');
>     return topContainerElement;
>   }

И вызывать в `PopupPresenter` так:

> const topContainerElement = this.popupComponent.getTopContainer();
> render(new FilmDetailsView(), topContainerElement);

А то если создавать отдельные вьюхи для них как будто лишнее.

2022-05-02 22:33 UTC, AlexMasterov commented on src/presenter/popap-presenter.js
> +    const commentsWrap = this.mainContainer.querySelector('.film-details__comments-wrap');
> Будет ли корректно в PopupView создать отдельные методы, которые ищут эти дочерние узлы?

На интенсиве это позволяет формально закрыть критерий, но по сути ничего не меняется и все проблемы остаются. Так иногда делают, можешь тоже создать такие методы :)

2022-05-02 22:34 UTC, AlexMasterov commented on src/presenter/popap-presenter.js
> +    const commentsWrap = this.mainContainer.querySelector('.film-details__comments-wrap');
Насколько мне известно, авторы курса до сих пор не предложили своего решения этой задачи, а решения наставников сочли непосильными для студентов. У самого есть несколько решений с кодом по сложности на уровне программы, как мне кажется.

<details>
<summary>Покажи пример</summary>

С ним твой код будет выглядеть так:
```js
export default class PopupView extends ChildrenView {
  constructor(film) {
    super();

    this._data = film;

    this.addChild('details', { view: FilmDetailsView, selector: '.film-details__top-container' });
    this.addChild('controls', { view: FilmControlsView, selector: '.film-details__top-container' });
    this.addChild('newComment', { view: NewCommentFormView, selector: '.film-details__comments-wrap' });
  }

  addComments(count) {
    const container = this.getElement().querySelector('.film-details__comments-list');

    while(count-- > 0) {
      render(new CommentView(), container);
    }
  }

  removeComments() {
    this.getElement().querySelector('.film-details__comments-list').innerHTML = '';
  }

  setFavoriteButtonClickHandler(callback) {
    this._children.controls.setFavoriteButtonClickHandler(callback);
  }

  // ...
}
```
</details>

Дочерний компонент описывается в `constructor`: имя объекта (= экземпляра класса) в `this._children` и позиция рендера для его элемента. Создание компонента будет _отложено_ до первого обращения к свойству с его именем, например, `this._children.controls`, или первому вызову `PopupView.getElement()`, в котором он также будет отрисован в указанное место. Если место не указано явно, то отрисуется в корне главного элемента. Дочерний элемент будет вместе с главным при вызове `PopupView.removeElement()`.

Добавление комментариев можно обыграть по-разному.

2022-05-02 22:45 UTC, AlexMasterov commented on src/presenter/popap-presenter.js
> +    const commentsWrap = this.mainContainer.querySelector('.film-details__comments-wrap');
В этом PR некоторые замечания скрыл, чтобы сделать необязательными к исправлению, потому что в начале интенсива их сложно учесть, а некоторые могут даже должным образом не проверить на защите проекте.

Поэтому пока достаточно только ознакомиться с этими критериями и узнать про проблемы.

2022-05-02 22:51 UTC, AlexMasterov commented
В этом PR некоторые замечания скрыл, чтобы сделать необязательными к исправлению, потому что в начале интенсива их сложно учесть, а некоторые могут даже должным образом не проверить на защите проекте.

Поэтому пока достаточно только ознакомиться с этими критериями и узнать про проблемы.

2022-05-03 15:23 UTC, AlexMasterov approved these changes
👍🏻

Пожалуйста, мелкие замечания в остатке доработай при выполнении следующего задания.

> Запоздалые рекомендации по разбивки разметки и компонентов пришлю отдельно 😃

2022-05-03 15:23 UTC, AlexMasterov commented on src/main.js
> +// const body = document.querySelector('body');
`//`

[`Б 18`](https://up.htmlacademy.ru/ecmascript/17/criteries#b18)
> В коде проекта нет файлов и частей кода, которые не используются, **включая закомментированные участки кода**

2022-05-03 15:23 UTC, AlexMasterov commented on src/view/popup-view.js
> +    return commentContainerElement;
<details>
<summary>view/popup-view.js</summary>

https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/b07f781a2f5fbd0649fae25a9772059fc50648bb/src/view/popup-view.js#L35-L40
https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/b07f781a2f5fbd0649fae25a9772059fc50648bb/src/view/popup-view.js#L44-L49
</details>

[`Д 11`](https://up.htmlacademy.ru/ecmascript/17/criteries#d11)
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции или вынесены из условий

Нужно упростить методы до одной строки:

```js
return this.getElement().querySelector('.film-details__top-container');
```

2022-05-03 15:23 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +      render(new CommentView(), commentsWrapElement);
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/166481582-503b6e16-63f0-4900-91a8-f4697cd40450.png)

</details>

<details>
<summary>Ожидание (markup/popup.html)</summary>

![image](https://user-images.githubusercontent.com/700213/166481822-e42b839b-6da3-4337-b5d7-cc117dea5a5f.png)

</details>

Нужно использовать другой узел для вставки комментариев.

<details>
<summary>Мой пример, где указан класс нужного узла</summary>

![image](https://user-images.githubusercontent.com/700213/166482023-f5d48116-e20b-4484-8843-65bd8afdc089.png)
![image](https://user-images.githubusercontent.com/700213/166482109-72e71f02-e045-46f6-966b-8f41d7f47b4d.png)

</details>

2022-05-03 15:23 UTC, merged