Шаблонизируй это
htmlacademy-ecmascript/977795-cinemaddict-17 pull request #4
Opened 2022-05-12 00:21 UTC by satananastyle

1. Разметка принимает данные извне
2. Изменены названия переменных для однообразия

2022-05-12 07:43 UTC, AlexMasterov requested changes

2022-05-12 07:43 UTC, AlexMasterov commented on src/view/footer-statistics-view.js
> +const createFooterStatisticsTemplate = (films) => (`<p>${films.length} movies inside</p>`);
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/168011014-76a44a17-82e7-43d0-90e9-108a8385778c.png)

</details>


<details>
<summary>Ожидание (markup/list.html)</summary>

![image](https://user-images.githubusercontent.com/700213/168010718-b3f82c24-0b83-45a5-bc3c-348a0d29bc5d.png)

</details>

Нужно учесть форматирование кол. фильмов из макета.

2022-05-12 07:43 UTC, AlexMasterov commented on src/view/footer-statistics-view.js
> +const createFooterStatisticsTemplate = (films) => (`<p>${films.length} movies inside</p>`);
`()`

Скобки здесь избыточны.

2022-05-12 07:43 UTC, AlexMasterov commented on src/view/footer-statistics-view.js
> +    this.films = films;
`this.films` = films;

Массивом с фильмами управляет модель. Если модель полностью обновит массив на новый, то его прошлая копия из-за дополнительной "ссылки" здесь продолжит занимать память.

В сам класс лучше сразу передавать количество фильмов.

2022-05-12 07:43 UTC, AlexMasterov commented on src/view/films-list-view.js
> +      <h2 class="films-list__title ${message === 'All movies.Upcoming' ? 'visually-hidden' : ''}">
`All movies.Upcoming`

См. макет:
https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/f2edc4537f86b71373d26b3daf695af65882b662/markup/list.html#L38

All movies.` `Upcoming

2022-05-12 07:43 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +    this.commentsList = [...filmsModel.getComments(this.openedFilm.comments.length)];
this.comments`List` = [...filmsModel.getComments(this.openedFilm.comments.length)];

[`Б 8`](https://up.htmlacademy.ru/ecmascript/17/criteries#b8)
> Массивы названы существительными во множественном числе

2022-05-12 07:43 UTC, AlexMasterov commented on src/presenter/films-presenter.js
> +    this.boardFilms = [...filmsModel.getFilms()];
this.`board`Films = [...filmsModel.getFilms()];

Избыточно.

> \+ в этом проекте нет _доски_, а есть _списки_

2022-05-12 07:43 UTC, AlexMasterov commented on src/mock/film.js
> +  id: 0,
id: `0`,

Должен быть _строкой_.

2022-05-12 07:43 UTC, AlexMasterov commented on src/main.js
> +const boardFilms = filmsModel.getFilms();
const `board`Films = filmsModel.getFilms();

🤔

2022-05-12 07:43 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +  init = (mainContainerElement, filmsModel) => {
<details>
<summary>presenter/popup-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/f2edc4537f86b71373d26b3daf695af65882b662/src/presenter/popup-presenter.js#L9-L14
</details>

На этом шаге советую попробовать сделать что-то вроде этого:

```js
// presenter/popup-presenter.js
export default class PopupPresenter {
  #commentsModel = null;

  constructor(commentsModel) {
    this.#commentsModel = commentsModel;
  }

  init = (film) => {
    const comments = this.#commentsModel.findByFilmId(film.id);

    render(this.popupComponent, document.body);
    // ...
  }
}
```
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/f2edc4537f86b71373d26b3daf695af65882b662/src/main.js#L13-L14
https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/f2edc4537f86b71373d26b3daf695af65882b662/src/main.js#L23-L24
</details>

```js
// main.js
const commentsModel = new CommentsModel();

const popupPresenter = new PopupPresenter(commentsModel);
const filmsPresenter = new FilmsPresenter(filmsModel, popupPresenter); 

filmsPresenter.init(siteMainElement); 
```

2022-05-16 21:37 UTC, satananastyle commented on src/presenter/popup-presenter.js
> +  init = (mainContainerElement, filmsModel) => {
Обязателен ли этот комментарий к исправлению в этой домашке? в следующей мы как раз будем реализовывать связь между карточкой фильма и попапом.

2022-05-16 21:43 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +  init = (mainContainerElement, filmsModel) => {
> Обязателен ли этот комментарий к исправлению в этой домашке? 

Нет. Это пример на будущие.

2022-05-16 22:16 UTC, AlexMasterov commented
👍🏻

2022-05-16 22:16 UTC, merged