Оживляет попап
htmlacademy-ecmascript/977795-cinemaddict-17 pull request #5
Opened 2022-05-25 02:00 UTC by satananastyle

1. Меняем функции в классах на Геттеры
2. Добавляем открытие и закрытие попапа по клику мышкой и ESC

2022-05-25 10:48 UTC, AlexMasterov requested changes

2022-05-25 10:48 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +    this.#comments = this.#filmsModel.getComments(this.#openedFilm.comments.length);
this.#filmsModel.getComments(`this.#openedFilm.comments.length`)

По итогу такая модель должна принимать `film.id` и на его основе возвращать связанные с ним комментарии.

2022-05-25 10:48 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +      this.delete();
<details>
<summary>presenter/popup-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/56866ca37297a2b90244896c6ed043a0ee607aa4/src/presenter/popup-presenter.js#L48

https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/56866ca37297a2b90244896c6ed043a0ee607aa4/src/presenter/popup-presenter.js#L35
</details>

Здесь метод `PopupPresenter.delete` вызывается без аргумента.

2022-05-25 10:48 UTC, AlexMasterov commented on src/presenter/films-presenter.js
> +    if (this.#films.length > 0) {
Для подобного действия можно у модели реализовать метод:

```js
- if (this.#films.length > 0) {
+ if (! this.#filmsModel.isEmpty()) {
```

В этом месте желательно инвертировать условие, убрав `!`:

```js
if (this.#filmsModel.isEmpty()) {
  // рендер списка с сообщением что он пустой
  return;
}
```

2022-05-25 10:48 UTC, AlexMasterov commented on src/presenter/films-presenter.js
> +      if (evt.key === 'Escape' || evt.key === 'Esc') {
Желательно реализовать функцию:
```diff
- if (evt.key === 'Escape' || evt.key === 'Esc') {
+ if (isEscapeEvent(evt)) {
```

2022-05-25 10:48 UTC, AlexMasterov commented on src/presenter/films-presenter.js
> +  #renderFilms = (film, filmsModel) => {
#renderFilms = (film, `filmsModel`) => {

`filmsModel` как зависимость самого `FilmsPresenter` уже передается в конструктор и доступна в методах через `this.#filmsModel`, а здесь является лишним параметром.

Нужно удалить.

2022-05-25 10:48 UTC, AlexMasterov commented on src/presenter/films-presenter.js
> +
<details>
<summary>presenter/films-presenter.j</summary>

https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/56866ca37297a2b90244896c6ed043a0ee607aa4/src/presenter/films-presenter.js#L39
https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/56866ca37297a2b90244896c6ed043a0ee607aa4/src/presenter/films-presenter.js#L50
</details>

<details>
<summary>presenter/popup-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/56866ca37297a2b90244896c6ed043a0ee607aa4/src/presenter/popup-presenter.js#L51-L52
</details>

Работа с `document.body` размазана на два объекта: один добавляет, а другой удаляет. Причем оба почему-то _знают_, что нужно делать 🤔

> Неудачное проектирование классов

2022-05-25 10:48 UTC, AlexMasterov commented on src/presenter/films-presenter.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/170240990-66d48ddd-9cd5-4889-9792-20ec039ec983.png)

</details>

Если закрыть попап с полной инфо. о фильме нажатием на кнопку с "крестиком", то на `document` остается обработчик для `keydown`.

> В рамках этого задание можно отложить

[`Б 36`](https://up.htmlacademy.ru/ecmascript/17/criteries#b36)
> Обработчики события добавляются и удаляются своевременно

2022-05-25 10:48 UTC, AlexMasterov commented on src/presenter/films-presenter.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/170241462-765505b3-928c-4d45-90d0-6e81c3f9c322.png)

</details>

Если открыть попап с полной инфо. о фильме и, не закрывая его, открыть другой, то на `document` накапливаются обработчики для `keydown`.

> В рамках этого задание можно отложить

[`Б 36`](https://up.htmlacademy.ru/ecmascript/17/criteries#b36)
> Обработчики события добавляются и удаляются своевременно

2022-05-25 10:48 UTC, AlexMasterov commented on src/presenter/films-presenter.js
> +    const onEscKeyDown = (evt) => {
Обращаю внимание, что во всем проекте для именования обработчиков событий _DOM_ нужно выбрать и использовать только один из двух форматов предложенных в критериях Д4 и Д6: `on*` **или** `*handler`.

Также далее не нужно путать с обработчики событий _DOM_ с обработчиками событий _компонентов_, которые устанавливаются через их публичные методы `set*Handler`. Последние считаются обычной функцией-коллбэком и для их именования применяется критерий Б9.

2022-05-25 10:48 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +    this.#closeButtonElement = this.#popupComponent.closeButton;
<details>
<summary>presenter/popup-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/56866ca37297a2b90244896c6ed043a0ee607aa4/src/presenter/popup-presenter.js#L14-L16
https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/56866ca37297a2b90244896c6ed043a0ee607aa4/src/presenter/popup-presenter.js#L29-L31
https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/56866ca37297a2b90244896c6ed043a0ee607aa4/src/presenter/popup-presenter.js#L55-L57
</details>

`this`.#topContainerElement = this.#popupComponent.`topContainer`;
и т.п.

См. https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/pull/3#discussion_r861886748:

> На интенсиве это позволяет формально закрыть критерий, но по сути ничего не меняется и все проблемы остаются

> **Это также создает ситуацию потенциальной утечки памяти**

Лучше отказаться от сохранения доч. элементов компонента в свойства (= `this.`) другого объекта. Даже если им предусмотрена их очистка.

2022-05-25 10:48 UTC, AlexMasterov commented on src/main.js
> +const films = filmsModel.films;
Если модель обновит массив фильмов на новый, то его старая версия продолжит заниматься память на протяжение всей работы приложения.

Не нужно здесь оставлять _ссылку_ на массив фильмов модели.  

https://github.com/htmlacademy-ecmascript/977795-cinemaddict-17/blob/56866ca37297a2b90244896c6ed043a0ee607aa4/src/main.js#L18

```diff
- new FooterStatisticsView(films.length)
+ new FooterStatisticsView(filmsModel.films.length)
```

> Для получения кол. фильмов в модели можно сделать спец. метод или геттер

2022-05-25 21:33 UTC, satananastyle commented on src/presenter/popup-presenter.js
> +    this.#comments = this.#filmsModel.getComments(this.#openedFilm.comments.length);
Йеп. Это временное решение для случайной генерации комментов

2022-05-29 19:23 UTC, AlexMasterov approved these changes

2022-05-29 19:23 UTC, merged